/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unvproject;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author fahad
 */

public class minimize extends javax.swing.JFrame {
    String name;
    String name2;
    String Clist;
    String fromrate;
    String torate;
    String torate2;
    float fromratef;
    float toratef;
    float toratef2;
    DBconnect db=new DBconnect();
    public minimize() {
        initComponents();
        //getContentPane().setBackground(Color.ORANGE);
       
        getdata();
        
        if(db.adminlogin==1){
            
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        convertbut = new javax.swing.JButton();
        fromnamelist = new javax.swing.JComboBox<>();
        tonamelist = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AmountText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        mini = new javax.swing.JToggleButton();
        undercoa = new javax.swing.JCheckBox();
        allwayson = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter[Project]");
        setBackground(new java.awt.Color(255, 153, 0));
        setLocation(new java.awt.Point(1, 1));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        convertbut.setText("convert");
        convertbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertbutActionPerformed(evt);
            }
        });

        fromnamelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromnamelistActionPerformed(evt);
            }
        });

        jLabel2.setText("From");

        jLabel4.setText("To");

        jLabel5.setText("Amount");

        jLabel7.setText("Result :");

        Result.setText("Null");

        mini.setSelected(true);
        mini.setText("minimize");
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });

        undercoa.setBackground(new java.awt.Color(255, 204, 51));
        undercoa.setText("undercoated");
        undercoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                undercoaMouseClicked(evt);
            }
        });

        allwayson.setBackground(new java.awt.Color(255, 204, 51));
        allwayson.setText("Allways on top");
        allwayson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allwaysonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fromnamelist, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tonamelist, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(convertbut, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mini, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allwayson)
                    .addComponent(undercoa))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromnamelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tonamelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allwayson, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undercoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromnamelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromnamelistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromnamelistActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

        
    }//GEN-LAST:event_formMouseEntered

    private void convertbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertbutActionPerformed
    convert();
    }//GEN-LAST:event_convertbutActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        
        
    }//GEN-LAST:event_jPanel1MouseEntered

    private void undercoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_undercoaMouseClicked
       checkboxunder();
    }//GEN-LAST:event_undercoaMouseClicked

    private void allwaysonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allwaysonMouseClicked
        checkboxunder1();
    }//GEN-LAST:event_allwaysonMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        minmize();
    }//GEN-LAST:event_miniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minimize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new minimize().setVisible(true);
            }
        });
    }
    public void convert(){
       try{
         getrate();
         fromratef = Float.parseFloat(fromrate);  
         toratef = Float.parseFloat(torate);
         toratef2 = Float.parseFloat(torate2);
         String check1;
        check1 = fromnamelist.getSelectedItem().toString();
        String check2;
        check2 = tonamelist.getSelectedItem().toString();
        float amount;
        amount = Float.parseFloat(AmountText.getText());
        float usd;
        float tocu;
        if(!check1.equals("USD") && !check2.equals("USD")){
            //converting the first selected currency to USD
            usd = (amount/fromratef);
            //converting to the secand selected currency
            tocu = (usd/toratef2);
            Result.setText(tocu+" "+check2);
            System.out.println(check2);
        }else if(check1.equals("USD") && !check2.equals("USD")){
            tocu = (amount/toratef2);
            Result.setText(tocu+" "+check2);
        }else if(!check1.equals("USD") && check2.equals("USD")){
            usd = (amount/fromratef);
            Result.setText(usd+" "+check2);
            System.out.println(fromratef);
        }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex);
       }
        
        
    }
    public void getrate(){
        try{
            name=fromnamelist.getSelectedItem().toString();
            name2=tonamelist.getSelectedItem().toString();
            String QF = ("select from_currency from exchange_rate where e_id='"+name+"'");
            String QT = ("select to_currency from exchange_rate where e_id='"+name+"'");
            String QT2 = ("select to_currency from exchange_rate where e_id='"+name2+"'");
            db.rs2 = db.st2.executeQuery(QF);
            db.rs3 = db.st3.executeQuery(QT);
            db.rs4 = db.st4.executeQuery(QT2);
            while(db.rs2.next()){
                fromrate = db.rs2.getString("from_currency");
                //fromrate.setText(db.rs2.getString("from_currency"));
                
            }while(db.rs3.next()){
                //torate.setText(db.rs3.getString("to_currency"));
                torate = db.rs3.getString("to_currency");
                
            }while (db.rs4.next()){
                torate2 = db.rs4.getString("to_currency");
            }
            
        }catch(Exception ex){
            //JOptionPane.showMessageDialog(null, ex);
        }
    }
public void getdata(){
    try{
     String Q = ("select currency_type from currency");
     db.rs = db.st.executeQuery(Q);  
     
     while(db.rs.next()){
         
         Clist=db.rs.getString(1);
         
         fromnamelist.addItem(Clist);
         tonamelist.addItem(Clist);
     }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
    } 
    
}
public void minmize(){
    if(mini.isSelected()){
        
        
    }else{
        Maininterface main=new Maininterface();
        main.setVisible(true);
        setVisible(false);
    }
}
public void checkboxunder(){
    //checking if the box ix checked , if checked it will make the form undercorated
    if(undercoa.isSelected()){
        
        dispose();
        setUndecorated(true);
        setVisible(true);
    }else if(!undercoa.isSelected()) {
        
        dispose();
        setUndecorated(false);
        setVisible(true);
    }
}
public void checkboxunder1(){
    //checking if the box is check , if checked it will make the form allways on top
    if(allwayson.isSelected()){
        setAlwaysOnTop(true);
    }else if(!allwayson.isSelected()){
        setAlwaysOnTop(false);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountText;
    private javax.swing.JLabel Result;
    private javax.swing.JCheckBox allwayson;
    private javax.swing.JButton convertbut;
    private javax.swing.JComboBox<String> fromnamelist;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton mini;
    private javax.swing.JComboBox<String> tonamelist;
    private javax.swing.JCheckBox undercoa;
    // End of variables declaration//GEN-END:variables
}
